// XIOM -- ChaCha20-based RNG (32-bit words)
// Copyright (c) 2026 Eleftherios Notas and XIOM Foundation
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// A deterministic PRNG that derives its output from ChaCha20 blocks.
// The 16-word state holds the "expand 32-byte k" constants, an 8-word key,
// a 32-bit block counter and a 96-bit nonce; each 64-byte keystream block is
// generated by 20 rounds (10 double-rounds) of quarter-round ARX operations.
// All arithmetic is clamped to 32 bits to emulate unsigned wrapping.

module xiom.rand.chacha

const _CHACHA_C0: Int = 0x61707865; // "expa"
const _CHACHA_C1: Int = 0x3320646e; // "nd 3"
const _CHACHA_C2: Int = 0x79622d32; // "2-by"
const _CHACHA_C3: Int = 0x6b206574; // "te k"

pub type ChaChaRng = {
  state: Vec[UInt32];
  pos: Int;
}

/// Mask a value to the lower 32 bits (emulates u32 in the i64 layer).
fn _u32w(x: Int) -> Int {
  return x & 0xFFFFFFFF;
}

/// 32-bit rotate left by n bits (n in 1..=16).
fn _rotl(x: Int, n: Int) -> Int {
  let v: Int = _u32w(x);
  return _u32w((v << n) | (v >> (32 - n)));
}

/// ChaCha20 quarter round over four state words (indices a, b, c, d).
fn _quarter_round(state: &mut Vec[UInt32], a: Int, b: Int, c: Int, d: Int) {
  let sa: Int = _u32w(state[a] as Int);
  let sb: Int = _u32w(state[b] as Int);
  let sc: Int = _u32w(state[c] as Int);
  let sd: Int = _u32w(state[d] as Int);
  let a1: Int = _u32w(sa + sb);
  let d1: Int = _rotl(sd ^ a1, 16);
  let c1: Int = _u32w(sc + d1);
  let b1: Int = _rotl(sb ^ c1, 12);
  let a2: Int = _u32w(a1 + b1);
  let d2: Int = _rotl(d1 ^ a2, 8);
  let c2: Int = _u32w(c1 + d2);
  let b2: Int = _rotl(b1 ^ c2, 7);
  state[a] = a2 as UInt32;
  state[b] = b2 as UInt32;
  state[c] = c2 as UInt32;
  state[d] = d2 as UInt32;
}

/// Generate one 16-word keystream block from the current 16-word state.
/// Private by design: callers use the public chacha_rng_* functions.
fn chacha_block(state: &Vec[UInt32]) -> Vec[UInt32] {
  var working = Vec[UInt32].new();
  var i: Int = 0;
  while i < 16 {
    working.push(state[i]);
    i = i + 1;
  }
  var round: Int = 0;
  while round < 10 {
    _quarter_round(&mut working, 0, 4, 8, 12);
    _quarter_round(&mut working, 1, 5, 9, 13);
    _quarter_round(&mut working, 2, 6, 10, 14);
    _quarter_round(&mut working, 3, 7, 11, 15);
    _quarter_round(&mut working, 0, 5, 10, 15);
    _quarter_round(&mut working, 1, 6, 11, 12);
    _quarter_round(&mut working, 2, 7, 8, 13);
    _quarter_round(&mut working, 3, 4, 9, 14);
    round = round + 1;
  }
  var out = Vec[UInt32].new();
  i = 0;
  while i < 16 {
    let wi: Int = _u32w(working[i] as Int);
    let si: Int = _u32w(state[i] as Int);
    out.push(_u32w(wi + si) as UInt32);
    i = i + 1;
  }
  return out;
}

/// Build the 16-word state: 4 constants, 8 key words, counter 0, nonce 0.
fn _make_state(key: &Vec[UInt32]) -> Vec[UInt32] {
  var st = Vec[UInt32].new();
  st.push(_CHACHA_C0 as UInt32);
  st.push(_CHACHA_C1 as UInt32);
  st.push(_CHACHA_C2 as UInt32);
  st.push(_CHACHA_C3 as UInt32);
  var i: Int = 0;
  while i < 8 {
    st.push(key[i]);
    i = i + 1;
  }
  st.push(0 as UInt32);
  st.push(0 as UInt32);
  st.push(0 as UInt32);
  st.push(0 as UInt32);
  return st;
}

/// Create a ChaCha RNG with an all-zero key (deterministic default).
/// Test vector: the first output word of the zero-key block is 0xADE0B876.
pub fn chacha_rng_new() -> ChaChaRng {
  var key = Vec[UInt32].new();
  var i: Int = 0;
  while i < 8 {
    key.push(0 as UInt32);
    i = i + 1;
  }
  var st = _make_state(&key);
  return ChaChaRng{ state: st; pos: 0; };
}

/// Create a ChaCha RNG from a 64-bit seed.
/// The seed's two 32-bit halves are replicated into the 8 key words.
pub fn chacha_rng_from_seed(seed: UInt64) -> ChaChaRng {
  var key = Vec[UInt32].new();
  let hi: Int = _u32w((seed >> 32) as Int);
  let lo: Int = _u32w(seed as Int);
  var i: Int = 0;
  while i < 8 {
    if i % 2 == 0 {
      key.push(hi as UInt32);
    } else {
      key.push(lo as UInt32);
    };
    i = i + 1;
  }
  var st = _make_state(&key);
  return ChaChaRng{ state: st; pos: 0; };
}

/// Return the next 32-bit output word.
/// `pos` tracks the position within the 64-word keystream window (16 words
/// per block, 4 blocks per window); the block counter advances at each
/// 16-word boundary.
pub fn chacha_rng_next_u32(r: &mut ChaChaRng) -> UInt32 {
  var ks = chacha_block(&r.state);
  let word: UInt32 = ks[r.pos % 16];
  r.pos = r.pos + 1;
  if r.pos % 16 == 0 {
    let c: Int = _u32w(r.state[12] as Int) + 1;
    r.state[12] = _u32w(c) as UInt32;
    if _u32w(r.state[12] as Int) == 0 {
      let c2: Int = _u32w(r.state[13] as Int) + 1;
      r.state[13] = _u32w(c2) as UInt32;
    };
  };
  if r.pos >= 64 {
    r.pos = 0;
  };
  return word;
}

/// Return the next value as a signed i64 in [0, 2^32).
pub fn chacha_rng_next_int(r: &mut ChaChaRng) -> Int {
  return _u32w(chacha_rng_next_u32(r) as Int);
}

/// Return the next value as a Float64 in [0, 1).
pub fn chacha_rng_next_float(r: &mut ChaChaRng) -> Float64 {
  let v: Int = _u32w(chacha_rng_next_u32(r) as Int);
  return (v as Float64) / 4294967296.0;
}

/// Return the next value in [0, hi). Requires hi > 0.
pub fn chacha_rng_next_bounded(r: &mut ChaChaRng, hi: Int) -> Int {
  if hi <= 0 {
    return 0;
  };
  let v: Int = _u32w(chacha_rng_next_u32(r) as Int);
  return v % hi;
}
