module p_sweep1

use xiom.async.io;
use xiom.bench;
use xiom.char;
use xiom.compress.gzip;
use xiom.contracts;
use xiom.convert.escape;
use xiom.convert.ip;
use xiom.convert.iri;
use xiom.convert.overflow;
use xiom.convert.utf;
use xiom.convert.uuid;
use xiom.convert.validate;
use xiom.convert.wstring;
use xiom.core;
use xiom.debug;
use xiom.debug.trace;
use xiom.error;
use xiom.ffi;
use xiom.ffi.c;
use xiom.ffi.dl;
use xiom.fmt;
use xiom.format.ansi;
use xiom.format.markup;
use xiom.format.numbering;
use xiom.format.terminal;
use xiom.format.text;
use xiom.format.textual;
use xiom.format.units;
use xiom.hash;
use xiom.io.console;
use xiom.io.fs;
use xiom.log;
use xiom.math.mathematical_logic;
use xiom.math.mathematical_physics;
use xiom.math.number_systems;
use xiom.math.signal;
use xiom.misc;
use xiom.net;
use xiom.num;
use xiom.os;
use xiom.os.args;
use xiom.os.event;
use xiom.rand;
use xiom.regex;
use xiom.serialize;
use xiom.serialize.yaml_lite;
use xiom.simd.mask;
use xiom.simd.vec4;
use xiom.simd.vec8;
use xiom.string;
use xiom.string.unicode;
use xiom.sync;
use xiom.text.transliterate;
use xiom.utf8;

fn main() -> Int {
  xiom.async.io.async_read_line(0);
  xiom.bench.bench_black_box_int(0);
  xiom.char.digit_value_to_char(0);
  xiom.compress.gzip.gzip_compress_file("");
  xiom.compress.gzip.gzip_decompress_file("");
  xiom.contracts.find_functions_using_type("");
  xiom.contracts.fn_has_contracts("");
  xiom.contracts.get_type_contracts("");
  xiom.contracts.type_has_invariants("");
  xiom.convert.escape.html_escape_attr("");
  xiom.convert.ip.string_to_ipv4("");
  xiom.convert.iri.iri_normalize("");
  xiom.convert.overflow.overflowing_neg(0);
  xiom.convert.utf.code_point_to_utf16(0);
  xiom.convert.uuid.uuid_parse("");
  xiom.convert.validate.is_valid_iban("");
  xiom.convert.wstring.from_wstring(0);
  xiom.convert.wstring.to_wstring("");
  xiom.convert.wstring.wstring_len(0);
  xiom.core.bool_to_int(false);
  xiom.core.int_to_bool(0);
  xiom.core.int_to_char_safe(0);
  xiom.debug.debug_print("");
  xiom.debug.log_debug("");
  xiom.debug.log_error("");
  xiom.debug.log_info("");
  xiom.debug.log_warn("");
  xiom.debug.trace_point("");
  xiom.debug.trace.trace_log("");
  xiom.error.error_message("");
  xiom.error.make_error("");
  xiom.ffi.safe_ptr_alloc(0);
  xiom.ffi.c.c_atof(0);
  xiom.ffi.c.c_atoi(0);
  xiom.ffi.dl.dl_close(0);
  xiom.fmt.format_bool(false);
  xiom.format.ansi.ansi_256_bg(0);
  xiom.format.ansi.ansi_cursor_left(0);
  xiom.format.ansi.ansi_cursor_right(0);
  xiom.format.markup.markup_parse_inline("");
  xiom.format.numbering.number_to_chinese_traditional(0);
  xiom.format.terminal.ansi_bg_256(0);
  xiom.format.terminal.ansi_cursor_back(0);
  xiom.format.terminal.ansi_cursor_forward(0);
  xiom.format.text.text_overline("");
  xiom.format.text.text_strikethrough("");
  xiom.format.textual.separator_dashed(0);
  xiom.format.textual.separator_double(0);
  xiom.format.textual.toc_indent(0);
  xiom.format.units.format_ms(0);
  xiom.hash.string_hash("");
  xiom.io.console.console_password("");
  xiom.io.console.console_set_title("");
  xiom.io.fs.fs_is_dir("");
  xiom.log.log_debug_msg("");
  xiom.log.log_enable_json(false);
  xiom.log.log_error_msg("");
  xiom.log.log_info_msg("");
  xiom.log.log_warn_msg("");
  xiom.log.set_output("");
  xiom.math.mathematical_logic.linear_logic("");
  xiom.math.mathematical_physics.gamma_matrices(0);
  xiom.math.number_systems.babylonian_numerals(0);
  xiom.math.number_systems.greek_numerals(0);
  xiom.math.number_systems.japanese_numerals(0);
  xiom.math.signal.window_bartlett(0);
  xiom.math.signal.window_blackman(0);
  xiom.math.signal.window_hanning(0);
  xiom.misc.reverse_str("");
  xiom.net.dns_lookup("");
  xiom.net.http_get_str("");
  xiom.net.http_status("");
  xiom.net.is_valid_port(0);
  xiom.net.url_parse_host("");
  xiom.net.url_parse_path("");
  xiom.net.url_parse_port("");
  xiom.net.url_parse_scheme("");
  xiom.num.digit_count(0);
  xiom.num.digit_sum(0);
  xiom.num.digital_root(0);
  xiom.num.euler_totient(0);
  xiom.num.f32_from_int(0);
  xiom.num.f64_from_int(0);
  xiom.num.fraction_from_int(0);
  xiom.num.fraction_from_str("");
  xiom.num.i128_from_i64(0);
  xiom.num.i16_from_i64(0);
  xiom.num.i32_from_i64(0);
  xiom.num.i64_abs(0);
  xiom.num.i64_signum(0);
  xiom.num.i8_from_i64(0);
  xiom.num.is_non_negative(0);
  xiom.num.is_palindrome_int(0);
  xiom.num.is_positive(0);
  xiom.num.prime_factors(0);
  xiom.num.reverse_int(0);
  xiom.num.u16_from_i64(0);
  xiom.num.u32_from_i64(0);
  xiom.num.u64_from_i64(0);
  xiom.num.u8_from_i64(0);
  xiom.os.disk_free("");
  xiom.os.disk_total("");
  xiom.os.env_unset("");
  xiom.os.file_size_bytes("");
  xiom.os.watch_file("");
  xiom.os.args.args_option("");
  xiom.os.event.epoll_close(0);
  xiom.os.event.kqueue_close(0);
  xiom.rand.random_bytes_crypto(0);
  xiom.regex.regex_escape_literal("");
  xiom.regex.regex_is_valid("");
  xiom.serialize.hex_str_to_bytes("");
  xiom.serialize.json_type_of("");
  xiom.serialize.yaml_lite.yaml_parse_document("");
  xiom.simd.mask.mask_from_bits(0);
  xiom.simd.vec4.f32x4_load(0);
  xiom.simd.vec8.f32x8_load(0);
  xiom.string.str_count_chars("");
  xiom.string.str_is_empty("");
  xiom.string.unicode.unicode_bidi_brackets("");
  xiom.string.unicode.unicode_bidi_scan("");
  xiom.string.unicode.unicode_casefold_turkic("");
  xiom.string.unicode.unicode_emoji_sequences("");
  xiom.string.unicode.unicode_line_breaks("");
  xiom.string.unicode.unicode_nfc_quick_check("");
  xiom.string.unicode.unicode_nfkc_quick_check("");
  xiom.string.unicode.unicode_normalize("");
  xiom.string.unicode.unicode_titlecase_word("");
  xiom.string.unicode.unicode_tolower_full("");
  xiom.string.unicode.unicode_toupper_full("");
  xiom.sync.cdl_new(0);
  xiom.sync.sem_new(0);
  xiom.text.transliterate.transliterate_arabic("");
  xiom.text.transliterate.transliterate_chinese_pinyin("");
  xiom.text.transliterate.transliterate_devanagari("");
  xiom.text.transliterate.transliterate_hebrew("");
  xiom.text.transliterate.transliterate_japanese_romaji("");
  xiom.text.transliterate.transliterate_korean_roman("");
  xiom.utf8.utf8_is_continuation(0);
  return 0;
}

