# same_leaf_audit.ps1 -- same-leaf public-type conflict inventory.
# Copyright (c) 2026 Eleftherios Notas and The XIOM Authors
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Scans xiom/**/*.xi for `pub type <Leaf> = { ... }` / `= enum { ... }`
# declarations, groups them by bare leaf, and reports the groups where two
# or more modules declare DIFFERENT shapes (the R44 collision class: codegen
# injects `%struct.<Leaf>` and clobbers fields when shapes differ).
#
# Usage:
#   pwsh tools/same_leaf_audit.ps1                 # summary to stdout
#   pwsh tools/same_leaf_audit.ps1 -OutFile <md>   # full markdown report
#
# Read-only; used by the compiler+stdlib R44 qualification slice and the
# dedup work. Re-run after any public-type change.
param(
  [string]$Root = "",
  [string]$OutFile = ""
)
if ($Root -eq "") { $Root = Join-Path (Split-Path -Parent $PSScriptRoot) "xiom" }
if (-not (Test-Path -LiteralPath $Root)) { Write-Output ("ERROR: root not found: " + $Root); exit 2 }

# Split a struct/enum body into fields/variants at top level: newlines and
# semicolons always separate; commas separate only outside ()/[] so generic
# and tuple types like Vec[(Int, Int)] stay one item. Fixes the former
# one-line-body parse gap (inline `pub type X = { a: Int; b: Int; }` used to
# count as a single field and produced false conflicts).
function Split-BodyItems([string]$body) {
  $items = @(); $cur = ""; $depth = 0
  foreach ($ch in $body.ToCharArray()) {
    if ($ch -eq '(' -or $ch -eq '[') { $depth++ }
    elseif (($ch -eq ')' -or $ch -eq ']') -and $depth -gt 0) { $depth-- }
    if ($ch -eq "`n" -or $ch -eq ';' -or ($ch -eq ',' -and $depth -eq 0)) {
      if ($cur.Trim() -ne '') { $items += $cur.Trim() }
      $cur = ""
    } else { $cur += $ch }
  }
  if ($cur.Trim() -ne '') { $items += $cur.Trim() }
  return $items
}

$decls = @()
foreach ($f in (Get-ChildItem -Path $Root -Filter *.xi -Recurse | Sort-Object FullName)) {
  $text = Get-Content -Raw -LiteralPath $f.FullName
  $mod = ([regex]::Match($text, '(?m)^module\s+(\S+)')).Groups[1].Value
  $rel = $f.FullName.Substring($Root.Length).TrimStart('\', '/')
  foreach ($m in [regex]::Matches($text, '(?s)pub type (\w+) = (enum )?\{([^{}]*)\}')) {
    $fields = @()
    foreach ($t in (Split-BodyItems $m.Groups[3].Value)) {
      $t = ($t -replace '//.*$', '').Trim()
      if ($t -ne '' -and $t -notmatch '^derive') { $fields += $t }
    }
    $canon = ((($fields -join '|') -replace '\s+', ' ') -replace '[\s,|]+$', '')
    $tokens = (($fields -join ',') -split '[,|]') |
      ForEach-Object { (($_ -replace '\s+', ' ').Trim() -replace '<', '[' -replace '>', ']') } |
      Where-Object { $_ -ne '' } | Sort-Object
    $decls += [pscustomobject]@{
      Leaf = $m.Groups[1].Value; Mod = $mod; File = $rel
      Kind = if ($m.Groups[2].Success) { 'enum' } else { 'struct' }
      Fields = $canon; Key = ($tokens -join ','); FieldCount = $fields.Count
    }
  }
}

$report = @()
$conflicts = @()
foreach ($g in ($decls | Group-Object Leaf | Where-Object { $_.Count -gt 1 })) {
  $shapes = $g.Group | ForEach-Object { "$($_.Kind):$($_.Key)" } | Sort-Object -Unique
  if ($shapes.Count -lt 2) { continue }
  $conflicts += $g.Name
  $report += "## $($g.Name)"
  $report += ""
  foreach ($d in ($g.Group | Sort-Object File)) {
    $report += ("- ``" + $d.File + "`` (" + $d.Mod + ", " + $d.Kind + ", " + $d.FieldCount + " fields): " + $d.Fields)
  }
  $report += ""
}

Write-Output ("same_leaf: decls=" + $decls.Count + " multi_decl_groups=" + (($decls | Group-Object Leaf | Where-Object { $_.Count -gt 1 }).Count) + " conflicting=" + $conflicts.Count)
if ($conflicts.Count -gt 0) { Write-Output ("conflicts: " + ($conflicts -join ', ')) }
if ($OutFile -ne "") {
  $header = "# Same-leaf public type conflicts (generated)`n`nGenerated by tools/same_leaf_audit.ps1 -- do not hand-edit.`n"
  Set-Content -LiteralPath $OutFile -Value ($header + "`n" + ($report -join "`n")) -Encoding ASCII
  Write-Output ("report: " + $OutFile)
}
